name: Build Portfolio

on:
  push:
    branches: [ modern-portfolio ]
  pull_request:
    branches: [ modern-portfolio ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/modern-portfolio'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
